sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -t jukim1124/docker-react-app -f Dockerfile.dev .

script: 
  - docker run -e CI=true jukim1124/docker-react-app npm run test -- --coverage